blank_issues_enabled: false
contact_links:
  - name: 🧑‍💻 Anikku help discord
    url: https://discord.gg/85jB7V5AJR
    about: Common questions are answered here
  - name: 🖥️ Aniyomi website
    url: https://aniyomi.org/
    about: Guides, troubleshooting, and answers to common questions
